version: '3'
services:
  tricarios-dev-db:
    image: 'postgres:14'
    restart: unless-stopped
    container_name: tricarios-dev-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tricarios-dev-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - tricarios-db-data:/var/lib/postgresql/data/

volumes:
  tricarios-db-data:
    name: tricarios-db-data
